### ISSUE TITLE
No new residential can be created

### ISSUE THREAD

**Issue by michaelachrisco** [AntonioND/ucity#6]
I love the game. Thanks again for making it. 

I seem to be having an issue with residentials. For some reason, on sameboy on ubuntu and miyoo mini plus, no matter what I do, no new residentials can be created:

No matter what I do, the R's stay just Rs and no new buildings will be created. I put the taxes to 0, I went to a predefined scenario and added more residentials, still no new housing. For some reason, no new residentials will ever be constructed. 
![image](https://github.com/AntonioND/ucity/assets/398491/a008ada5-aefd-488c-817d-e154204d2f7b)
This is just one example. I am using  ucity.gbc on 1.2 release.

**Comment by AntonioND** [comment]
Hi! I'm glad you like the game. :)

It looks like your problem is lack of services around the residential areas. You need to add police stations, hospitals, etc. The radius of effect of the services isn't as big as you'd like, probably. You can check the minimap from the START menu to check if your residential tiles are under the effect of your services or not.

For more information about what is exactly needed, check the manual. It's a bit short, but it mentions this part in particular: https://github.com/AntonioND/ucity/blob/master/manual.rst#services

**Comment by michaelachrisco** [comment]
Ok thanks!
